### ISSUE TITLE
Analytics Link Issue

### ISSUE THREAD

**Issue by brettallred** [spree-contrib/spree_analytics_trackers#11]
When spree is mounted to a location other than the root, such as /shop, the analytics link in the backend still points to the root ```/admin/analytics``` rather than ```/shop/admin/analytics```

**Comment by rodrigoargumedo** [comment]
Does it happen in all analytic services or some of them? Can you also provide a screenshot with a stack trace of the error?

**Comment by dylanfisher** [comment]
Also ran into this issue. The URL shouldn't be hard coded. 

brettallred's fix looks good and matches spree's method of rendering the sidebar items https://github.com/spree/spree/blob/38930cf96ddfed8f5e7e3ba9153c904d6687d430/backend/app/views/spree/admin/shared/sub_menu/_product.html.erb

**Comment by ronzalo** [comment]
@dylanfisher it works, but the pull request failed in travis because of factory_girl ._.
