### ISSUE TITLE
Add original SHA1 digest to deface overrides to suppress warnings

### ISSUE THREAD

**Issue by dylanfisher** [spree-contrib/spree_analytics_trackers#13]
Per deface instructions, a `original` digest should be added to overrides https://github.com/spree/deface#optional.

> `:original` - Either a string containing the original markup that is being overridden, or a string that is the SHA1 digest of the original markup. If supplied Deface will log when the original markup changes, which helps highlight overrides that need attention when upgrading versions of the source application. Only really warranted for :replace overrides. NB: All whitespace is stripped before comparison. To generate the SHA1 digest do: `Digest::SHA1.hexdigest(original_markup_string.gsub(/\s/, ''))`

This will suppress the following warnings:

```
Deface: [WARNING] No :original defined for 'add_product_viewed_to_products_show', you should change its definition to include:
 :original => '26c5598ea2dc0d899b0dfc07a0f32998c861e9e4' 
```

**Comment by damianlegawiec** [comment]
Fixed via https://github.com/spree-contrib/spree_analytics_trackers/pull/16
