### ISSUE TITLE
Could not find generator 'spree_analytics_trackers:install'

### ISSUE THREAD

**Issue by AmitPatel-BoTreeConsulting** [spree-contrib/spree_analytics_trackers#20]
After installing `~> 1.0`, when I run `'spree_analytics_trackers:install`, it gives following error

`Could not find generator 'spree_analytics_trackers:install'. Maybe you meant 'spree_gateway:install', 'canonical_rails:install' or 'spree:auth:install'`

I use it with `Rails 5.2` and `Spree 3.7`

**Comment by theunraveler** [comment]
Duplicate of https://github.com/spree-contrib/spree_analytics_trackers/issues/19, I think.

**Comment by damianlegawiec** [comment]
Fixed!
