### ISSUE TITLE
undefined method `ga_enabled?'

### ISSUE THREAD

**Issue by MateoLa** [spree-contrib/spree_analytics_trackers#60]
The homepage renders ok.

When I try to login I get the following error:
ActionView::Template::Error (undefined method `ga_enabled?' for #<#<Class:0x00007f6e7076bd40>:0x00007f6e70769d10>):
    1: <title><%= title %></title><% if ga_enabled? %>

In my Gemfile: gem 'spree_analytics_trackers', '~> 2.0'
After bundle update: Using spree_analytics_trackers 2.1.0

In my console: 
Deface: 'add_segment_page_tracker_to_body' matched 1 times with 'meta'
Deface: [ERROR] The original source for 'add_segment_page_tracker_to_body' has changed, this override should be reviewed to ensure it's still valid.
Deface: 'add_segment_initializer_to_layout' matched 1 times with 'title'
Deface: [ERROR] The original source for 'add_segment_initializer_to_layout' has changed, this override should be reviewed to ensure it's still valid.
Deface: 'add_google_analytics_page_viewed_to_spree_application' matched 1 times with 'meta'
Deface: [ERROR] The original source for 'add_google_analytics_page_viewed_to_spree_application' has changed, this override should be reviewed to ensure it's still valid.
Deface: 'add_google_analytics_initializer_to_spree_application' matched 1 times with 'title'
Deface: [ERROR] The original source for 'add_google_analytics_initializer_to_spree_application' has changed, this override should be reviewed to ensure it's still valid.
Deface: 'add_js_links_to_head' matched 1 times with 'erb[loud]:contains("yield :head")'
Deface: [WARNING] No :original defined for 'add_js_links_to_head', you should change its definition to include:
 :original => 'd91b8ae6a9087306e0eda074df22b05dc6aaf76c' 
Deface: 'add_ecommerce_tracking_js_tag' matched 1 times with 'erb[loud]:contains("javascript_include_tag 'spree/frontend/all'")'
---> This should't be the origin for the error but I commented anyway.

If I go one version back:
  In gemfile: gem 'spree_analytics_trackers', '~> 2.0.0'
  And delete, "remove_from_cart_analytics.js" from vendor/assets/javascript/spree/frontend/all.js
  And restart the server.
The error go away

**Comment by damianlegawiec** [comment]
Thanks for reporting this @MateoLa 👍

**Comment by channainfo** [comment]
I have the same problem after upgrading to Spree 4.2.0-rc4 and spree_analytics_trackers 2.1.0

**Comment by damianlegawiec** [comment]
fixed!

**Comment by estraph** [comment]
Any idea when this will be released?

**Comment by estraph** [comment]
Disregard the question, apparently this was already released in v2.1.1 https://github.com/spree-contrib/spree_analytics_trackers/pull/59
